# Pengantar Metode Numerik {#intro}

Bagian ini akan menjelaskan tentang gambaran umum metode numerik. 

## Penyelesaian Persoalan Matematika 
 
Dalam dunia ilmu pengetahuan, ada banyak persoalan yang dapat dimodelkan secara matematis. Model matematika yang dihasilkan ada yang berupa model sederhana dan terkadang berupa model yang cukup rumit. Secara umum, ada dua metode yang dapat dilakukan untuk menyelesaikan model matematika, yaitu **metode analitik** dan **metode numerik**. 

**1. Metode Analitik**
Metode analitik biasa digunakan untuk menyelesaikan permasalahan model matematika yang sederhana dengan menggunakan rumus-rumus aljabar yang sudah baku. 
Misalnya, apabila kita diberikan soal untuk mencari akar-akar polinom berderajad 2 seperti $x^2+3x+3=0$. Untuk mencari akar-akar polinom tersebut, kita dapat menggunakan pendekatan faktorisasi atau dengan rumus *abc*.

**2. Metode Numerik**
Metode numerik cenderung digunakan untuk membantu dalam penyelesaian model matematika yang rumit yang tidak dapat diselesaikan menggunakan metode analitik. Terkadang model matematika yang rumit masih dapat diselesaikan dengan pendekatan analitik, akan tetapi dengan proses penyelesaian yang rumit dan tidak efisien.Pada metode numerik, teknik penyelesaian dilakukan menggunakan operasi hitungan (tambah, kurang, kali, bagi).
Berikut ini merupakan contoh persoalan matematika yang dapat diselesaikan dengan metode numerik:

a. Mencari akar-akar persamaan polinom: 

$23.4x^7-1.25x^6+120x^4+15x^3-120x^2-x+100=0$

b. Mencari nilai integral tentu dari: 

$\int_{1.2}^{2.5} (\sqrt{(45.3e^{7x}+\frac{100}{x})^4}+\frac{4}{(x^2+1)} \,dx$

**Metode Analitik versus Metode Numerik**

| Perbedaan    | Metode Analitik    | Metode Numerik     |
| :------------- | :----------: | -----------: |
| Persoalan | Sederhana | Sederhana maupun rumit |
| Metode Penyelesaian   | Menggunakan rumus aljabar yang sudah baku | Menggunakan operasi hitungan aritmatika biasa (+,-,x,:) |
| Solusi | Solusi sejati (galat = 0) | Solusi pendekatan (dengan galat) |
| Hasil akhir | Berupa fungsi | Berupa angka |


## Tahap Penyelesaian Numerik

Penyelesaian persoalan dengan pendekatan numerik dapat dilakukan dengan enam tahap berikut:

1. *Pemodelan*

    Tahap pemodelan dilakukan dengan memodelkan permasalahan dari dunia nyata ke dalam persamaan matematika, seperti model linier atau non-linier.
    
2. *Penyederhanaan Model*

    Pada tahap ini, dilakukan proses penyederhanaan model dari hasil pemodelan tahap pertama apabila model yang diperoleh masih terlalu rumit, seperti masih terdapat banyak variabel.
    
3. *Formulasi Numerik*

    Tahap formulasi numerik diimplementasikan dengan menentukan metode numerik yang akan dipakai secara bersama dengan analisis eror awal (berupa perkiraan eror, penentuan ukuran langkah, dsb.). Setelah itu, baru kemudian disusun algoritme berdasarkan metode numerik yang telah ditentukan.
    
4. *Pemrograman*

    Hasil formulasi yang telah didapat kemudian diterjemahkan ke dalam bahasa pemrograman tertentu.
    
5. *Operasional*

    Program komputer yang telah dibuat kemudian diujicobakan dengan data stimulasi dan hasilnya dievaluasi. Setelah diperloleh hasil yang telah sesuai, selanjutnya dioperasikan dengan data yang sebenarnya.
    
6. *Evaluasi*

    Hasil yang telah diperoleh kemudian diinterpretasikan dengan menganalisis hasil keluaran program dan membandingkannya dengan prinsip dasar untuk memperkirakan kualitas solusi numerik yang dihasilkan.
    
## Analisis Eror
