---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
# Pengantar Metode Numerik {#intro}

Bagian ini akan menjelaskan tentang gambaran umum metode numerik. 

## Penyelesaian Persoalan Matematika 
 
Dalam dunia ilmu pengetahuan, ada banyak persoalan yang dapat dimodelkan secara matematis. Model matematika yang dihasilkan ada yang berupa model sederhana dan terkadang berupa model yang cukup rumit. Secara umum, ada dua metode yang dapat dilakukan untuk menyelesaikan model matematika, yaitu **metode analitik** dan **metode numerik**. 

1. **Metode Analitik**

    Metode analitik biasa digunakan untuk menyelesaikan permasalahan model matematika yang sederhana dengan menggunakan rumus-rumus aljabar yang sudah baku. Misalnya, apabila kita diberikan soal untuk mencari akar-akar polinom berderajad 2 seperti $x^2+3x+3=0$. Untuk mencari akar-akar polinom tersebut, kita dapat menggunakan pendekatan faktorisasi atau dengan rumus *abc*.

2. **Metode Numerik**

    Metode numerik cenderung digunakan untuk membantu dalam penyelesaian model matematika yang rumit yang tidak dapat diselesaikan menggunakan metode analitik. Terkadang model matematika yang rumit masih dapat diselesaikan dengan pendekatan analitik, akan tetapi dengan proses penyelesaian yang rumit dan tidak efisien. Pada metode numerik, teknik penyelesaian dilakukan menggunakan operasi hitungan (tambah, kurang, kali, bagi). Berikut ini merupakan contoh persoalan matematika yang dapat diselesaikan dengan metode numerik:

    a. Mencari akar-akar persamaan polinom: 
    
       $23.4x^7-1.25x^6+120x^4+15x^3-120x^2-x+100=0$

    b. Mencari nilai integral tentu dari: 
        
       $\int_{1.2}^{2.5} (\sqrt{(45.3e^{7x}+\frac{100}{x})^4}+\frac{4}{(x^2+1)} \,dx$

**Metode Analitik versus Metode Numerik**

| Perbedaan    | Metode Analitik    | Metode Numerik     |
| :------------- | :----------: | -----------: |
| Persoalan | Sederhana | Sederhana maupun rumit |
| Metode Penyelesaian   | Menggunakan rumus aljabar yang sudah baku | Menggunakan operasi hitungan aritmatika biasa (+,-,x,:) |
| Solusi | Solusi sejati (galat = 0) | Solusi pendekatan (dengan galat) |
| Hasil akhir | Berupa fungsi | Berupa angka |


## Tahap Penyelesaian Numerik

Penyelesaian persoalan dengan pendekatan numerik dapat dilakukan dengan enam tahap berikut:

1. **Pemodelan**

    Tahap pemodelan dilakukan dengan memodelkan permasalahan dari dunia nyata ke dalam persamaan matematika, seperti model linier atau non-linier.
    
2. **Penyederhanaan Model**

    Pada tahap ini, dilakukan proses penyederhanaan model dari hasil pemodelan tahap pertama apabila model yang diperoleh masih terlalu rumit, seperti masih terdapat banyak variabel.
    
3. **Formulasi Numerik**

    Tahap formulasi numerik diimplementasikan dengan menentukan metode numerik yang akan dipakai secara bersama dengan analisis eror awal (berupa perkiraan eror, penentuan ukuran langkah, dsb.). Setelah itu, baru kemudian disusun algoritme berdasarkan metode numerik yang telah ditentukan.
    
4. **Pemrograman**

    Hasil formulasi yang telah didapat kemudian diterjemahkan ke dalam bahasa pemrograman tertentu.
    
5. **Operasional**

    Program komputer yang telah dibuat kemudian diujicobakan dengan data stimulasi dan hasilnya dievaluasi. Setelah diperloleh hasil yang telah sesuai, selanjutnya dioperasikan dengan data yang sebenarnya.
    
6. **Evaluasi**

    Hasil yang telah diperoleh kemudian diinterpretasikan dengan menganalisis hasil keluaran program dan membandingkannya dengan prinsip dasar untuk memperkirakan kualitas solusi numerik yang dihasilkan.
    
## Analisis Galat

Dalam metode numerik, kita hanya mendapatkan solusi persalahan yang mendekati solusi sebenarnya sehingga solusi numerik disebut dengan **solusi pendekatan** atau **solusi hampiran** atau disebut pula dengan *(approximation)*. Solusi hampiran ini tidak persis tepat dengan solusi sebenarnya, sehingga terdapat selisih antara solusi hampiran dengan solusi sebenarnya. Selisih ini disebut dengan **galat** atau **eror**. Semakin kecil nilai eror, maka solusi numerik yang didapatkan akan semakin teliti.

Pengukuran galat dapat dibagi menjadi dua, yaitu *galat absolut* dan *galat relatif*.

1. **Galat Absolut**

    Galat absolut atau eror mutlak merupakan selisih antara nilai sebenarnya $(x)$ dengan nilai perkiraan $(x')$. Galat absolut dapat didefinisikan dalam persamaan \@ref(eq:erorAbsolut):

\begin{equation*} 
  \epsilon_{A} = \lvert x-x' \rvert
  (\#eq:erorAbsolut)
\end{equation*} 


2. **Galat Relatif**

    Galat relatif diperoleh dengan membagi selisih nilai sebenarnya $(x)$ dan nilai perkiraan $(x')$ dengan nilai sebenarnya. Persamaan galat relatif dapat didefinisikan sebagai \@ref(eq:erorRelatif1)

    \begin{equation*} 
      \epsilon_{R} = \left| \frac{x-x'}{x} \right|
       (\#eq:erorRelatif1)
    \end{equation*}

    atau dalam persentase,

    \begin{equation*} 
      \epsilon_{R} = \left| \frac{x-x'}{x} \times 100 \% \right|
      (\#eq:erorRelatif2)
    \end{equation*}

    Galat relatif di atas dinormalkan terhadap nilai sebenarnya/nilai sejati, sehingga dapat disebut pula dengan **galat relatif sejati**.

    Dalam praktik di dunia nyata, kita tidak mengetahui nilai sebenarnya $(x)$, oleh karena itu nilai galat $(\epsilon)$ sering dinormalkan terhadap solusi pendekatannya, sehingga galat relatifnya disebut dengan **galat relatif pendekatan**:

    \begin{equation*} 
      \epsilon_{R} = \left| \frac{\epsilon}{x'} \right|
      (\#eq:erorRelatif3)
    \end{equation*}

**Contoh 1:**

Misal diketahui nilai sejati adalah $\frac{10}{3}$ dan nilai pendekatan $3.333$. Hitunglah:

1. Galat
2. Galat absolut
3. Galat relatif
4. Galat relatif pendekatan

**Solusi**

1. Galat = $\frac{10}{3} - 3.333 = \frac{10}{3} - \frac{3333}{1000} = \frac{1}{3000} = 0.000333$
2. Galat absolut = $\lvert 0.000333 \rvert = 0.000333$
3. Galat relatif = $\frac{1/3000}{10/3} = \frac{1}{1000} = 0.0001$
4. Galat relatif pendekatan = $\frac{1/3000}{3.333} = \frac{1}{9999}$

Perhitungan numerik yang menggunakan pendekatan *iterasi*, galat relatif pendekatan dihitung dengan persamaan 

\begin{equation*} 
  \epsilon_{RA} = \left| \frac{x_{r+1}-x_{r}}{x_{r+1}} \right|
  (\#eq:erorIterasi)
\end{equation*}

di mana, $x_{r+1}$ merupakan nilai pendekatan iterasi saat ini dan $x_{r}$ merupakan nilai pendekatan iterasi sebelumnya.

Proses iterasi ini akan dihentikan apabila $\lvert \epsilon_{RA} \rvert < \epsilon_{s}$, dengan $\epsilon_{s}$ adalah nilai toleransi yang telah ditentukan. Nilai $\epsilon_{s}$ yang semakin kecil akan memberikan solusi yang semakin teliti, namun dengan iterasi yang semakin tinggi.

**Contoh 2:**

Diketahui prosedur iterasi pada persamaan berikut:

\begin{equation*}
    x_{r+1}=\frac{-x_{r}^3+3}{6}, r=0,1,2,3,\ldots
\end{equation*}

Misal diberikan $x_{0}=0.5$ dan toleransi $\epsilon_{s} = 0.00001$, maka diperoleh iterasi sebagai berikut:

\begin{equation*}
   x_{0}=0.5 \\
   x_{1}=0.4791667; \left| \epsilon_{RA}=\frac{x_{1}-x_{0}}{x_{1}} \right| = 0.043478 > \epsilon_{s} \\
   x_{2}=0.4816638; \left| \epsilon_{RA}=\frac{x_{2}-x_{1}}{x_{2}} \right| = 0.0051843 > \epsilon_{s} \\
   x_{3}=0.4813757; \left| \epsilon_{RA}=\frac{x_{3}-x_{2}}{x_{3}} \right| = 0.0005984 > \epsilon_{s} \\
   x_{4}=0.4814091; \left| \epsilon_{RA}=\frac{x_{4}-x_{3}}{x_{4}} \right| = 0.0000693 > \epsilon_{s} \\
   x_{5}=0.4814052; \left| \epsilon_{RA}=\frac{x_{5}-x_{4}}{x_{5}} \right| = 0.0000081 < \epsilon_{s} \\
\end{equation*}

Pada iterasi ke-5, iterasi dihentikan karena $\lvert \epsilon_{RA} \rvert < \epsilon_{s}$ sudah terpenuhi.

## Jenis Galat

1. **Galat pemotongan** 

    Galat pemotongan *(truncation error)* terjadi karena adanya pemotongan suatu proses matematika yang tak berhingga. Tipe galat pemotongan bergantung pada metode komputasi yang digunakan untuk pendekatan sehingga disebut juga galat metode.
Misalnya, diketahui suatu Deret Taylor yang dipotong sampai suku orde ke-n:

    \begin{equation*}
      f(x) \approx f(x_{0}+ \frac{x-x_{0}}{1!}f'(x_{0}) +\frac{(x-x_{0})^2}{2!}f''(x_{0}) + \ldots +             \frac{x-x_{0}^n}{n!}f^{n}(x_{0}) + R_{n}(x))
    \end{equation*}

    yang mana $R_{n}(x)$ merupakan galat atau sisa (residu),

    \begin{equation*}
       R_{n}(x) = \frac{(x-x_{0})^{n+1}}{(n+1)!}f^{n+1}(c) \:\:\:, x_{0}<c<x
    \end{equation*}

2. **Galat pembulatan**

    Galat pembulatan *(round-off error)* terjadi karena adanya keterbatasan bilangan yang dinyatakan dalam bentuk angka atau digit dalam aplikasi (mesin hitung dan komputer).
    
    Contoh: $\frac{1}{3}$ dinyatakan dalam $0,333...3$

3. **Galat total**

    Galat total diperoleh dari jumlah antara galat pemotongan dan galat pembulatan.
    
    Contoh: $cos(0,2) \approx 1-\frac{(0,2)^2}{2} + \frac{(0,2)^4}{24} \approx 0,980067$

    Pada contoh, galat pemotongan terjadi karena kita menghampiri $cos(0,2)$ sampai dengan suku orde empat. Adapun galat pembulatan terjadi karena dilakukan pembulatan nilai hampiran ke dalam 7 digit bena.


## Angka Bena

**Angka bena** dapat didefinisikan sebagai angka penting dan memiliki makna yang dapat digunakan secara pasti.

**Contoh:**

$43,123$ memiliki 5 angka bena (4,3,1,2,3)

$0,1764$ memiliki 4 angka bena (1,7,6,4)

$0,0000012$ memiliki 2 angka bena (1,2)

$278,300$ memiliki 6 angka bena (2,7,8,3,00)

$270,0090$ memiliki 7 angka bena (2,7,0,0,0,9,0)

$0,0090$ memiliki 2 angka bena (9 dan 0)

$1360; 1,360; 0,001360$ masing-masing memiliki 4 angka bena

Jumlah angka bena dapat ditentukan berdasarkan pada jumlah digit *mantis*-nya.

**Contoh:**

$4,3123 \times 10^1$ memiliki 5 angka bena

$1,764 \times 10^{-1}$ memiliki 4 angka bena

$1,2 \times 10^{-6}$ memiliki 2 angka bena

$2,78300 \times 10^2$ memiliki 6 angka bena

$0,2700090 \times 10^3$ memiliki 7 angka bena

$9,0 \times 10^3$ memiliki 2 angka bena

$13,60 \times 10^2$; $0,1360 \times 10^1$; $1,360 \times 10^3$ memiliki 4 angka bena

$6,02 \times 10^{23}$ memiliki 24 angka bena

$1,5 \times 10^7$ memiliki 8 angka bena


## Sistem Bilangan

### Biner
Komputer merepresentasikan suatu bilangan riil ke dalam sebuah representasi biner 64-digit. Berikut ini merupakan ilustrasi dari representasi biner 64-digit.

\begin{equation*}
    \color{orange}{0}\; \color{blue}{10000000011}\; \color{red}{1011100100010000000000000000000000000000000000000000}
\end{equation*}

Representasi biner di atas dapat diformulasikan sebagai berikut,

\begin{equation*}
    (-1)^{\color{orange}{s}} 2^{\color{blue}{c}-1023}(1+\color{red}{f})
\end{equation*}

Dengan $\color{orange}s$ merupakan <span style="color:orange">bit pertama</span> yang mengindikasikan tanda, $\color{blue}c$ adalah <span style="color:blue">11-bit</span> yang disebut dengan karakteristik, dan $\color{red}f$ adalah <span style="color:red">52-bit</span> pecahan biner yang disebut dengan *mantissa*.

**Contoh:**

Diketahui representasi biner berikut,
\begin{equation*}
    \color{orange}{0}\; \color{blue}{10000000011}\; \color{red}{1011100100010000000000000000000000000000000000000000}
\end{equation*}

Berdasarkan representasi tersebut, kita memiliki $\color{orange}{s=0}$ yang mengindikasikan bilangan positif. Adapun 11 bit selanjutnya $(\color{blue}{10000000011})$ mengindikasikan karakteristik,

\begin{equation*}
    c=1\cdot 2^{10} + 0\cdot 2^9 + \dotsc + 0 \cdot 2^2 + 1\cdot 2^1 + 1 \cdot 2^0=1024+2+1=1027,
\end{equation*}

sehingga, $2^{1027-1023}=2^4$

Selanjutnya, 52 bits terakhir merupakan mantisa.

\begin{equation*}
    f=1\ldots \left(\frac{1}{2}\right)^1 + 1\ldots \left(\frac{1}{2}\right)^3 + 1\ldots \left(\frac{1}{2}\right)^4 + 1\ldots \left(\frac{1}{2}\right)^5 + 1\ldots \left(\frac{1}{2}\right)^8 +
    1\ldots \left(\frac{1}{2}\right)^{12}.
\end{equation*}

Sehingga,

\begin{align*}
    (-1)^s 2^{c-1023}(1+f)&=(-1)^0 2^{1027-1023}\left(1+\left( \frac{1}{2} + \frac{1}{8} + \frac{1}{16} + \frac{1}{32} + \frac{1}{256} + \frac{1}{4096}\right)\right) \\
    &=27.56640625.
\end{align*}

Namun demikian, angka mesin setelahnya yang paling kecil direpresentasikan sebagai berikut,
\begin{equation*}
    0\; 10000000011\; 1011100100001111111111111111111111111111111111111111,
\end{equation*}

dan angka mesin setelahnya yang paling besar adalah,
\begin{equation*}
    0\; 10000000011\; 1011100100010000000000000000000000000000000000000001.
\end{equation*}

Hal tersebut berarti bahwa, angka mesin pertama yang kita dapatkan tidak hanya merepresentasikan $27,56640625$, namun juga setengah dari bilangan riil di antara $27,56640625$ dan angka mesin berikutnya yang terkecil, serta setengah dari angka di antara $27,56640625$ dan angka mesin berikutnya yang terbesar. Dengan kata lain, hal ini merepresentasikan bilangan riil apapun di dalam interval berikut,

$[27.5664062499999982236431605997495353221893310546875,\\
27.5664062500000017763568394002504646778106689453125]$

Dalam hal ini, kita ketahui bahwa mesin tidak dapat secara tepat merepresentasikan bilangan riil yang sebenarnya.

Bilangan positif paling kecil yang dinormalisasi yang dapat direpresentasikan memiliki $s=0, \: c=1, \: \text{dan} \: f=0$ yang ekuivalen dengan,

\begin{equation*}
        2^{-1022}\cdot (1+0) \approx 0.22251 \times 10^{-307}. 
    \end{equation*}

dengan demikian, angka berapapun yang kurang dari,

\begin{equation*}
  2^{-1022}\cdot(1+0)
\end{equation*}

akan menghasilkan keadaan *underflow* dan biasanya dinyatakan menjadi 0.

dan bilangan positif ternormalisasi terbesar memiliki $s=0, \: c=2046, \: \text{dan} \: f=1-2^{-52}$ yang ekuivalen dengan,

 \begin{equation*}
        2^{1023}\cdot (2-2^{-52}) \approx 0.17977 \times 10^{309}. 
    \end{equation*}

sehingga, angka berapapun yang lebih besar dari,

\begin{equation*}
        2^{1023}\cdot (2-2^{-52})
    \end{equation*}

akan menghasilkan keadaan *overflow* dan mengakibatkan proses perhitungan terhenti.

### Desimal

Bilangan riil dalam komputer biasa disajikan dalam format bilangan titik kambang. Bilangan titik kambang disajikan dengan cacah digit *berarti* yang sudah tetap. Digit *berarti* di sini merupakan angka bena yang sudah dijelaskan pada subbab sebelumnya.

Di sini, kita asumsikan bahwa bilangan dalam komputer disajikan dalam bilangan titik kambang ternomalisasi berikut,

\begin{equation*}
        \pm0.d_1d_2\dotsc d_k\times 10^n, \;\;\; 1\leq d_1\leq 9, \;\;\;\text{and}\;\;\; 0\leq d_i \leq 9.
    \end{equation*}
    
dengan $d_{1}d_{2}d_{3} \ldots d_{k}$ merupakan bit mantisa.

Setiap bilangan real positif dalam interval yang diberikan oleh mesin dapat dinormalisasi menjadi,

\begin{equation*}
    y = 0.d_1d_2 \dotsc d_k d_{k+1} d_{k+2} \dotsc \times 10^n.
\end{equation*}

Bentuk bilangan titik kambang $y$, dinotasikan sebagai $fl(y)$, diperoleh dengan mengakhiri mantisa $y$ pada digit desimal $k$. Secara umum, ada dua teknik yang biasa digunakan, yaitu **pemenggalan *(chopping)* ** dan **pembulatan *(rounding)* **. 

1. *Pemenggalan* 
    
    Pemenggalan dilakukan dengan memenggal digit $d_{k+1}d_{k+2}$, sehingga menghasilkan,
    
    \begin{equation*}
        fl(y)=0.d_1d_2\dotsc d_k\times 10^n.
    \end{equation*}
    
2. *Pembulatan*

    Pembulatan dilakukan dengan menambahkan $5 \times 10^{n-(k+1)}$ terhadap $y$ kemudian selanjutnya dilakukan pemotongan untuk menghasilkan,
    
    \begin{equation*}
        fl(y)=0.\delta_1\delta_2\dotsc\delta_k \times 10^n.
    \end{equation*}

    Dalam pembulatan, ada beberapa ketentuan, di antaranya:
    * jika $d_{k+1} \geq 5$, tambahkan 1 terhadap $d_{k}$ *(pembulatan ke atas/round up)*
    * jika $d_{k+1} \leq 5$, lakukan pemotongan terhadap seluruh digit kecuali $k$ digit pertama *(pembulatan ke bawah/round down dan $\delta_i=d$)*
    
    
**Contoh**
    
Bilangan $\pi$ memiliki bentuk ekspansi desimal tak hingga sebagai berikut,
    
$\pi = 3,14159265 \ldots$ 

yang mana dapat dituliskan ke dalam bentuk ternormalisasi

$\pi = 0,314159265 \ldots \times 10^1$

Bentuk bilangan titik kambang $\pi$ dengan pemenggalan 5 digit adalah

\begin{equation*}
    fl(\pi)=0.31415 \times 10^1 = 3.1415.
\end{equation*}
    
Sedangkan Bentuk bilangan titik kambang $\pi$ dengan pembulatan 5 digit adalah *(perhatikan bahwa digit keenam dari ekspansi desimal $\pi$ adalah 9)*

\begin{equation*}
    fl(\pi)=(0.31415 + 0.00001) \times 10^1 = 3.1416.
\end{equation*}
    
    
### Aritmetika bilangan titik kambang 

**1. Penjumlahan**
    
*Contoh:*

Hitunglah $x+y$ jika diketahui $x = 1,557$ dan $y=0,04381$ dengan mantisa 4 digit (basis 10)!

*Solusi:*

\begin{align*}
  0,1557 \times 10^1 + 0.4381 \times 10^{-1} &= 0,1557 \times 10^1 + 0,004381 \times 10^1 \\
  &= 0,160081 \times 10^1
  \end{align*}

*Pemenggalan/chopping* $\rightarrow 0,1600 \times 10^1$

*Pembulatan/rounding* $\rightarrow 0,1601 \times 10^1$

Galat mutlak pemenggalan $= \left| (0.160081 \times 10^1)-(0.1600 \times 10^1) \right| = 0.000081$

Galat mutlak pembulatan $= \left| (0.160081 \times 10^1)-(0.1601 \times 10^1) \right| = 0.000019$


**2. Pengurangan**

*Contoh:*

Hitunglah $0.56780 \times 10^5 - 0.56430 \times 10^5$ (5 angka bena)!

*Solusi:*

$0.56780 \times 10^5 - 0.56430 \times 10^5 = 0.00350 \times 10^5$

Hasil dinormalisasi menjadi $0.350 \times 10^3$ dengan 3 angka bena.

*Chopping* $\rightarrow 0.350 \times 10^3$

*Rounding* $\rightarrow 0.350 \times 10^3$

**3. Perkalian**

*Contoh:*

Hitung perkalian $0,4652 \times 10^4$ dengan $0,1456 \times 10^{-1}$ (4 angka bena)!

*Solusi:*

* Kalikan mantis: $0,4652 \times 0,1456 = 0,06773312$
* Jumlahkan pangkat: $4+(-1)=3$
* Gabungkan mantis dengan pangkat: $0,06773312 \times 10^3$
* Normalisasi: $0,6773312 \times 10^2$
* *Chopping* $\rightarrow 0.6773 \times 10^2$
* *Rounding* $\rightarrow 0.6773 \times 10^2$

**4. Pembagian**

*Contoh:*

Hitung pembagian $0,8675 \times 10^{-4}$ dengan $0,2543 \times 10{-2}$ (4 angka bena)!

*Solusi:*

* Bagi mantis: $0,8675 \times 0,2543 = 3,4113252$
* Kurangkan pangkat: $-4+(-2)=-2$
* Gabungkan mantis dengan pangkat: $3,4113252 \times 10^{-2}$
* Normalisasi: $0,34113252 \times 10^{-1}$
* *Chopping* $\rightarrow 0.3411 \times 10^{-1}$
* *Rounding* $\rightarrow 0.3411 \times 10^{-1}$

    

## Referensi

1. Munir, R. (2013). **Metode Numerik Revisi ketiga**. Informatika.
2. Burden, Richard L and Faires, J. Douglas. (2010). **Numerical Analysis Ninth Edition**. Brooks/Cole, Cengage Learning.
3. Scott, L. Ridgway. (2016). **Numerical Analysys Second Edition**. Princeton University Press.
